// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPmqY79PNaIuUhlFpdtHEgPTnkcB8nioM',
    appId: '1:958716915105:web:99767b249fbae1e8412fe0',
    messagingSenderId: '958716915105',
    projectId: 'quiz-app-d5558',
    authDomain: 'quiz-app-d5558.firebaseapp.com',
    storageBucket: 'quiz-app-d5558.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkbCiE8bSymOYV06X19T4Z2p1Z5I5aQo',
    appId: '1:958716915105:android:72121b5c406a9fe9412fe0',
    messagingSenderId: '958716915105',
    projectId: 'quiz-app-d5558',
    storageBucket: 'quiz-app-d5558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2sqek6npAPOqD-MjA2Hi0Tzsbtm80IJM',
    appId: '1:958716915105:ios:7fa07103213d7167412fe0',
    messagingSenderId: '958716915105',
    projectId: 'quiz-app-d5558',
    storageBucket: 'quiz-app-d5558.appspot.com',
    androidClientId: '958716915105-l7iavct089aj5n02aor3u0basgdehn3j.apps.googleusercontent.com',
    iosClientId: '958716915105-dm3g1tbe1uisbeqedcslehthh549u5ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2sqek6npAPOqD-MjA2Hi0Tzsbtm80IJM',
    appId: '1:958716915105:ios:7fa07103213d7167412fe0',
    messagingSenderId: '958716915105',
    projectId: 'quiz-app-d5558',
    storageBucket: 'quiz-app-d5558.appspot.com',
    androidClientId: '958716915105-l7iavct089aj5n02aor3u0basgdehn3j.apps.googleusercontent.com',
    iosClientId: '958716915105-dm3g1tbe1uisbeqedcslehthh549u5ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
